version: '2.1'

services:
    php:
        extends:
            file: ../base.yml
            service: app
        container_name: php
        image: php:fpm-alpine
        volumes:
            - ../../src/public_html:/var/www/html
            - ./conf/php-fpm.d/10-env_vars.conf:/usr/local/etc/php-fpm.d/10-env_vars.conf
            - ./init.sh:/init.sh
        restart: always
        ports:
             - 9001
#            - 9000
        entrypoint: ['/bin/sh', '/init.sh']